# Generated by Django 4.1.1 on 2022-11-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=1, max_digits=15)),
                ('photo', models.ImageField(upload_to='pictures/%Y/%m/%d/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('availability', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
                'ordering': ['-created_at'],
            },
        ),
    ]
